#ifndef CONFIG_KEYMAP_H
#define CONFIG_KEYMAP_H

#define KEYBOARD_NAME Ubmk65

#define SLEEP_DELAY 600

#define WAKEKUP_KEY_NUM 2

#define HID_BLE_SPEED 3

#define TX_POWER 0

#endif // CONFIG_KEYMAP_H